### ISSUE TITLE
the models errors

### ISSUE THREAD

**Issue by oxm** [uber-research/DeepPruner#2]
Traceback (most recent call last):
  File "submission_kitti.py", line 83, in <module>
    model.load_state_dict(state_dict['state_dict'], strict=True)
  File "/home/xxm/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepPruner:

**Comment by ShivamDuggal4** [comment]
Hi @oxm , is this the entire error message? If not, could you please post the entire error message.

Potentially, the error could be because the 'models/config.py' hasn't been set according to the type of the model and the dataset you want to run.

Please check 'models/config.py' and set it according to your use-case.
'cost_aggregator_scale' should be 4 for DeepPruner-best-* and 8 for DeepPruner-fast-*

**Comment by oxm** [comment]
yes，you are right
