### ISSUE TITLE
Issue in reading pfm files

### ISSUE THREAD

**Issue by nakul3112** [uber-research/DeepPruner#36]
HI @ShivamDuggal4 ,
  
 I am implementing deep pruner from this repository for stereo disparity estimation. However, in data loading step, I am having errors related to reading pfm file. Even though the directory sturcture is as per the scene_collector.py file, I am not able to get past reading the data in following line in train_sceneflow.py.

Line 208: for batch_idx, (imgL_crop, imgR_crop, disp_crop_L) in enumerate(TrainImgLoader):

Any help would be greatly appreciated.

Regards,
Nakul

**Comment by ShivamDuggal4** [comment]
Hi @nakul3112 

The code for reading the `pfm files` is mentioned here: https://github.com/uber-research/DeepPruner/blob/master/deeppruner/dataloader/readpfm.py

Are you testing on Sceneflow dataset images or some custom images ?
Could be please share the entire error traceback you are getting ? That would allow me debug the issue you are getting.

Best Regards
Shivam

**Comment by nakul3112** [comment]
Hi @ShivamDuggal4 ,

    Yes, I am using Sceneflow dataset for testing. Actually, I was able to use the pretrained and finetuned DeepPruner models you mentioned in the repository, and I directly run the `submission_kitti.py` script for getting disparity images. Hence there is no need to solve this read_pfm issue as of now, thanks. However, I would be glad to ask further queries I have:

 1) Do you by any chance have tried to convert the pretrained models to **TorchScript** or **ONNX** format, which later can be used for writing inference code in C++? Any leads on this will be greatly appreciated.

Regards,
Nakul

**Comment by ShivamDuggal4** [comment]
Hi @nakul3112 

Sorry, I have not tried converting the models to TorchScript or ONNX format, and I am not aware of anyone who can provide quick help for the same.

I do agree that having an ONNX version of DeepPruner models would be useful for many people (reason being even faster inference time), and we do have an open issue for the same: https://github.com/uber-research/DeepPruner/issues/37
It would probably be useful to have a single and separate issue for the ONNX export request. Since we already have an open issue for that, I would close the previous issue of pfm files.

Feel free to post any further findings/ issues regarding ONNX model export on this issue: https://github.com/uber-research/DeepPruner/issues/37

Best Regards
Shivam
